name: Build Satis

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Satis
        run: composer create-project composer/satis:dev-main --no-dev --stability=dev

      - name: Build
        run: php satis/bin/satis build satis.json output
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.SATIS_TOKEN }}"}}'

      - uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - id: deployment
        uses: actions/deploy-pages@v4